### ISSUE TITLE
Can't upgrade 1.0B1 to 1.b1

### ISSUE THREAD

**Issue by wildintellect** [kbgg/qgis-stac-browser#38]
QGIS tells me there's a new version, but the upgrade doesn't work. I'm not sure if the plugin manager handles letters in version numbering or not. This is the only plugin I've ever seen with a letter. Might be an upstream bug.

Also I can't find which branch in this repo has either version number, all the code still shows 0.1

**Comment by kbgg** [comment]
The plugin uploaded in its current state is still a beta version, hence the 'b' in the version number.
I wasn't aware when I uploaded the plugin but it appears that adding this letter to the version number changes the way the QGIS parses the version number. 1.0B1 gets translated to 1.b1 and since they're not equal strings it gets reported as a new version.

I'll be removing this version from the plugin repository and upload a proper 1.0.0 this week which should fix this. I'll leave this issue open until that happens.

Thanks for reporting!

**Comment by kbgg** [comment]
1.0.0 is uploaded now and is live on the QGIS Plugin Repository. This should be fixed now.

**Comment by wildintellect** [comment]
Super funny, QGIS tells me it's a downgrade, but it let me do it anyways... suggestion, next plugin just go with 0.1 or 0.9 before the 1.0 Thanks for the quick responses.
